/**
 * Few-shot examples for Coach AI drill generation.
 * Four examples covering both drill types, multiple shot areas, and different HCP bands.
 * Each matches the simplified drillSchema.
 */

export const coachDrillExamples = [
  {
    drill_type: "points" as const,
    title: "Aggressive Putting 4-6m",
    goal: "Become a more aggressive putter within 6 meters with good speed control.",
    icon: "target",
    time_minutes: 15,
    shot_area: "putting",
    setup_steps: [
      "Place a hole on a flat section of the practice green.",
      "Mark three distances: 4m, 5m, and 6m from the hole.",
      "Use a different spot for every putt.",
    ],
    rules: [
      "Distances cycle: 4m → 5m → 6m → repeat.",
      "Choose a different spot for every putt.",
      "Reach 15 points to finish. Score = total putts taken (fewer is better).",
      "Short putts and missed return putts incur heavy penalties.",
    ],
    outcomes: [
      { label: "Holed", points: 3 },
      { label: "Good Pace", points: 1 },
      { label: "Long + Made", points: 0 },
      { label: "Short", points: -3 },
      { label: "Long + Miss", points: -3 },
      { label: "4-Putt+", points: -5 },
    ],
    target_points: 15,
    distances: [4, 5, 6],
    end_condition: "Drill ends when you reach 15 points.",
    lower_is_better: true,
    hcp: { input: "15", value: 15, band: "13_to_20" as const },
  },
  {
    drill_type: "score_entry" as const,
    title: "Easy Chip Drill",
    goal: "Build consistency on simple chip shots from a fairway lie.",
    icon: "figure.golf",
    time_minutes: 10,
    shot_area: "chipping",
    setup_steps: [
      "Find a flat fairway lie about 10 meters from a hole.",
      "Use one wedge for all chips.",
    ],
    rules: [
      "Chip from 10m from a fairway lie.",
      "Count consecutive chips stopping within one wedge length of the hole.",
      "One miss resets the streak.",
    ],
    score_label: "Consecutive Chips",
    score_unit: "chips",
    prompt: "How many chips in a row stopped within one wedge length of the hole?",
    lower_is_better: false,
    hcp: { input: "15", value: 15, band: "13_to_20" as const },
  },
  {
    drill_type: "score_entry" as const,
    title: "Fairway Finder: 10-Ball Dispersion Test",
    goal: "Test driving accuracy under pressure with a 10-shot sample.",
    icon: "scope",
    time_minutes: 15,
    shot_area: "driver",
    setup_steps: [
      "Set up on the range with a target fairway corridor about 25m wide.",
      "Place an alignment stick at your target line.",
      "Mark fairway boundaries with two objects 12.5m either side of center.",
    ],
    rules: [
      "Hit 10 drives aiming at the target corridor.",
      "Count only drives that land or finish within the 25m fairway corridor.",
      "You must score at least 7/10 to pass the drill.",
      "If you score under 5, narrow the corridor to 20m next session.",
    ],
    score_label: "Fairways Hit",
    score_unit: "out of 10",
    prompt: "How many of your 10 drives finished within the fairway corridor?",
    lower_is_better: false,
    hcp: { input: "4", value: 4, band: "0_to_5" as const },
  },
  {
    drill_type: "points" as const,
    title: "Bunker Escape Artist",
    goal: "Build confidence getting out of greenside bunkers on the first attempt.",
    icon: "flame",
    time_minutes: 10,
    shot_area: "bunker",
    setup_steps: [
      "Find a greenside bunker with a flat lie.",
      "Place a towel on the green about 5m from the bunker edge as your target.",
      "Drop balls in the bunker with a reasonable lie for each shot.",
    ],
    rules: [
      "Hit bunker shots aiming for the towel on the green.",
      "Reach 10 points to complete the drill.",
      "Streak bonus: 2 'Out and close' results in a row earns +2 bonus points.",
      "If you leave 3 balls in the bunker during the drill, restart from 0 points.",
    ],
    outcomes: [
      { label: "Out and within 2m of towel", points: 3 },
      { label: "Out and on green", points: 1 },
      { label: "Out but missed green", points: 0 },
      { label: "Still in bunker", points: -2 },
    ],
    target_points: 10,
    distances: [5],
    end_condition: "Drill ends when you reach 10 points.",
    lower_is_better: true,
    hcp: { input: "26", value: 26, band: "21_to_30" as const },
  },
];
