/**
 * Few-shot examples for Coach AI drill generation.
 * Examples deliberately show DIFFERENT drill structures to avoid repetitive output.
 * Each matches the simplified drillSchema.
 */

export const coachDrillExamples = [
  {
    drill_type: "score_entry" as const,
    title: "Survival Putting 3m",
    goal: "Build clutch putting under increasing pressure from a single fixed distance.",
    icon: "bolt.fill",
    time_minutes: 10,
    shot_area: "putting",
    setup_steps: [
      "Place a tee 3 meters from the hole.",
      "Use a different break for each set of 5 putts (move the tee to a new angle).",
    ],
    rules: [
      "All putts from 3m. No distance changes — pressure comes from the scoring.",
      "Start with 10 points. Holed = +1, miss = −2.",
      "If your score drops to 0, the drill ends immediately — you are eliminated.",
      "Survive 20 putts without hitting 0 to complete the drill.",
      "Enter your final score (0 if eliminated, otherwise points remaining after 20 putts).",
    ],
    score_label: "Final Score",
    score_unit: "points",
    prompt: "What was your final score? (0 if eliminated, or points remaining after 20 putts)",
    lower_is_better: false,
    hcp: { input: "15", value: 15, band: "13_to_20" as const },
  },
  {
    drill_type: "points" as const,
    title: "Make or Break 2m",
    goal: "Build confidence on the putts that matter most — holing out from 2 meters.",
    icon: "target",
    time_minutes: 10,
    shot_area: "putting",
    setup_steps: [
      "Place a coin 2 meters from the hole on a straight putt.",
      "Use the same line for all putts. Move to a breaking putt after reaching 6 points if you want extra challenge.",
    ],
    rules: [
      "All putts from 2m. Simple make or miss.",
      "Reach 6 points to complete the drill.",
    ],
    outcomes: [
      { label: "Holed", points: 2 },
      { label: "Missed", points: -1 },
    ],
    target_points: 6,
    distances: [2],
    end_condition: "Drill ends when you reach 6 points.",
    lower_is_better: true,
    hcp: { input: "15", value: 15, band: "13_to_20" as const },
  },
  {
    drill_type: "score_entry" as const,
    title: "Three-Foot Confidence Builder",
    goal: "Build a reliable short putt stroke by tracking makes from 1 meter.",
    icon: "hand.thumbsup.fill",
    time_minutes: 10,
    shot_area: "putting",
    setup_steps: [
      "Place a coin 1 meter from the hole.",
      "Choose 4 different angles around the hole (front, back, left, right) and mark each with a tee.",
    ],
    rules: [
      "Putt 5 balls from each of the 4 positions (20 putts total).",
      "Count how many you hole out of 20.",
      "Target for high-handicappers: 14 out of 20.",
      "If you hole fewer than 10, move closer to 0.75m and repeat.",
    ],
    score_label: "Putts Holed",
    score_unit: "out of 20",
    prompt: "How many of your 20 putts from 1 meter did you hole?",
    lower_is_better: false,
    hcp: { input: "28", value: 28, band: "21_to_30" as const },
  },
  {
    drill_type: "score_entry" as const,
    title: "Easy Chip Drill",
    goal: "Build consistency on simple chip shots from a fairway lie.",
    icon: "figure.golf",
    time_minutes: 10,
    shot_area: "chipping",
    setup_steps: [
      "Find a flat fairway lie about 10 meters from a hole.",
      "Use one wedge for all chips.",
    ],
    rules: [
      "Chip from 10m from a fairway lie.",
      "Count consecutive chips stopping within one wedge length of the hole.",
      "One miss resets the streak.",
    ],
    score_label: "Consecutive Chips",
    score_unit: "chips",
    prompt: "How many chips in a row stopped within one wedge length of the hole?",
    lower_is_better: false,
    hcp: { input: "15", value: 15, band: "13_to_20" as const },
  },
  {
    drill_type: "score_entry" as const,
    title: "Fairway Finder: 10-Ball Dispersion Test",
    goal: "Test driving accuracy under pressure with a 10-shot sample.",
    icon: "scope",
    time_minutes: 15,
    shot_area: "driver",
    setup_steps: [
      "Set up on the range with a target fairway corridor about 25m wide.",
      "Place an alignment stick at your target line.",
      "Mark fairway boundaries with two objects 12.5m either side of center.",
    ],
    rules: [
      "Hit 10 drives aiming at the target corridor.",
      "Count only drives that land or finish within the 25m fairway corridor.",
      "You must score at least 7/10 to pass the drill.",
      "If you score under 5, narrow the corridor to 20m next session.",
    ],
    score_label: "Fairways Hit",
    score_unit: "out of 10",
    prompt: "How many of your 10 drives finished within the fairway corridor?",
    lower_is_better: false,
    hcp: { input: "4", value: 4, band: "0_to_5" as const },
  },
  {
    drill_type: "points" as const,
    title: "Bunker Escape Artist",
    goal: "Build confidence getting out of greenside bunkers on the first attempt.",
    icon: "flame",
    time_minutes: 10,
    shot_area: "bunker",
    setup_steps: [
      "Find a greenside bunker with a flat lie.",
      "Place a towel on the green about 5m from the bunker edge as your target.",
      "Drop balls in the bunker with a reasonable lie for each shot.",
    ],
    rules: [
      "Hit bunker shots aiming for the towel on the green.",
      "Reach 10 points to complete the drill.",
      "Streak bonus: 2 'Within 2m' results in a row earns +2 bonus points.",
      "If you leave 3 balls in the bunker during the drill, restart from 0 points.",
    ],
    outcomes: [
      { label: "Within 2m", points: 3 },
      { label: "On green", points: 1 },
      { label: "Missed green", points: 0 },
      { label: "Still in bunker", points: -2 },
    ],
    target_points: 10,
    distances: [5],
    end_condition: "Drill ends when you reach 10 points.",
    lower_is_better: true,
    hcp: { input: "26", value: 26, band: "21_to_30" as const },
  },
];
